/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./app/**/*.{js,jsx,ts,tsx}", "./src/**/*.{js,jsx,ts,tsx}", "./components/**/*.{js,jsx,ts,tsx}", "./App.{js,jsx,ts,tsx}"],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      colors: {
        "on-secondary-fixed-variant": "#574500",
        "on-primary": "#ffffff",
        "champagne-gold": "#D4AF37",
        "surface-container-low": "#f6f3f5",
        "error": "#ba1a1a",
        "on-error": "#ffffff",
        "secondary-container": "#fed65b",
        "on-tertiary-container": "#b37c59",
        "primary": "#00081e",
        "on-background": "#1b1b1d",
        "border-gray": "#C6C6C8",
        "surface-container-high": "#eae7ea",
        "surface-bright": "#fcf8fb",
        "tertiary-fixed-dim": "#f8b992",
        "outline": "#75777f",
        "error-container": "#ffdad6",
        "on-secondary-container": "#745c00",
        "primary-fixed": "#d9e2ff",
        "background": "#fcf8fb",
        "secondary": "#735c00",
        "on-secondary": "#ffffff",
        "tertiary-container": "#391700",
        "surface-gray": "#F2F2F7",
        "on-error-container": "#93000a",
        "on-tertiary-fixed-variant": "#673c1e",
        "inverse-primary": "#b4c6f4",
        "surface-container-highest": "#e4e2e4",
        "outline-variant": "#c5c6cf",
        "on-tertiary-fixed": "#311300",
        "system-green": "#34C759",
        "on-primary-container": "#7687b2",
        "surface-tint": "#4c5e86",
        "glass-bg": "rgba(255, 255, 255, 0.7)",
        "secondary-fixed": "#ffe088",
        "system-red": "#FF3B30",
        "secondary-fixed-dim": "#e9c349",
        "royal-navy": "#0A1F44",
        "on-secondary-fixed": "#241a00",
        "surface-container-lowest": "#ffffff",
        "on-surface-variant": "#44464e",
        "tertiary-fixed": "#ffdbc7",
        "surface-dim": "#dcd9dc",
        "surface-variant": "#e4e2e4",
        "on-primary-fixed-variant": "#34466d",
        "on-surface": "#1b1b1d",
        "inverse-on-surface": "#f3f0f2",
        "surface": "#fcf8fb",
        "inverse-surface": "#303032",
        "on-tertiary": "#ffffff",
        "surface-container": "#f0edef",
        "tertiary": "#150500",
        "primary-fixed-dim": "#b4c6f4",
        "primary-container": "#0a1f44",
        "on-primary-fixed": "#041a3f"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px",
        "squircle": "24px"
      },
      spacing: {
        "margin-mobile": "16px",
        "gutter": "16px",
        "card-gap": "24px",
        "margin-desktop": "32px",
        "unit": "8px"
      },
      fontFamily: {
        "body-sm": ["Inter"],
        "label-caps": ["Inter"],
        "display-lg-mobile": ["Inter"],
        "display-lg": ["Inter"],
        "body-lg": ["Inter"],
        "headline-md": ["Inter"],
        "numeric-xl": ["Inter"]
      },
      fontSize: {
        "body-sm": ["15px", {"lineHeight": "20px", "fontWeight": "400"}],
        "label-caps": ["12px", {"lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "600"}],
        "display-lg-mobile": ["28px", {"lineHeight": "34px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "display-lg": ["34px", {"lineHeight": "41px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "body-lg": ["17px", {"lineHeight": "22px", "fontWeight": "400"}],
        "headline-md": ["22px", {"lineHeight": "28px", "letterSpacing": "-0.01em", "fontWeight": "600"}],
        "numeric-xl": ["40px", {"lineHeight": "48px", "letterSpacing": "-0.03em", "fontWeight": "700"}]
      }
    },
  },
  plugins: [],
}
